sudo: false

language: php

branches:
  except:
    - /^release-\d+\.\d+\.\d+.*$/
    - /^ghgfk-.*$/

cache:
  directories:
    - $HOME/.composer/cache

env:
  global:
    - TESTS_ZEND_DB_ADAPTER_DRIVER_MYSQL_HOSTNAME=localhost
    - TESTS_ZEND_DB_ADAPTER_DRIVER_MYSQL_PASSWORD=
    - TESTS_ZEND_DB_ADAPTER_DRIVER_PGSQL_HOSTNAME=localhost

matrix:
  include:
    - php: 5.5
      env:
        - EXECUTE_CS_CHECK=true
    - php: 5.5
      env:
        - EVENT_MANAGER_VERSION:'^2.6.2'
        - HYDRATOR_VERSION='^1.1'
        - SERVICE_MANAGER_VERSION='^2.7.5'
    - php: 5.6
      env:
        - EXECUTE_TEST_COVERALLS=true
    - php: 5.6
      env:
        - EVENT_MANAGER_VERSION='^2.6.2'
        - HYDRATOR_VERSION='^1.1'
        - SERVICE_MANAGER_VERSION='^2.7.5'
    - php: 7
    - php: 7
      env:
        - EVENT_MANAGER_VERSION='^2.6.2'
        - HYDRATOR_VERSION='^1.1'
        - SERVICE_MANAGER_VERSION='^2.7.5'
    - php: 7.1
    - php: 7.1
      env:
        - EVENT_MANAGER_VERSION='^2.6.2'
        - HYDRATOR_VERSION='^1.1'
        - SERVICE_MANAGER_VERSION='^2.7.5'
    - php: 7.2
    - php: 7.2
      env:
        - EVENT_MANAGER_VERSION='^2.6.2'
        - HYDRATOR_VERSION='^1.1'
        - SERVICE_MANAGER_VERSION='^2.7.5'
  allow_failures:
    - php: 7.2

notifications:
  email: false

before_install:
  - if [[ $EXECUTE_TEST_COVERALLS != 'true' ]]; then phpenv config-rm xdebug.ini || return 0 ; fi
  - composer self-update
  - if [[ $EXECUTE_TEST_COVERALLS == 'true' ]]; then composer require --dev --no-update satooshi/php-coveralls ; fi
  - if [[ $EVENT_MANAGER_VERSION != '' ]]; then composer require --dev --no-update "zendframework/zend-eventmanager:$EVENT_MANAGER_VERSION" ; fi
  - if [[ $EVENT_MANAGER_VERSION == '' ]]; then composer require --dev --no-update "zendframework/zend-eventmanager:^3.0" ; fi
  - if [[ $HYDRATOR_VERSION != '' ]]; then composer require --no-update "zendframework/zend-stdlib:^2.7" ; fi
  - if [[ $HYDRATOR_VERSION != '' ]]; then composer require --dev --no-update "zendframework/zend-hydrator:$HYDRATOR_VERSION" ; fi
  - if [[ $HYDRATOR_VERSION == '' ]]; then composer require --dev --no-update "zendframework/zend-hydrator:^2.1" ; fi
  - if [[ $SERVICE_MANAGER_VERSION != '' ]]; then composer require --dev --no-update "zendframework/zend-servicemanager:$SERVICE_MANAGER_VERSION" ; fi
  - if [[ $SERVICE_MANAGER_VERSION == '' ]]; then composer require --dev --no-update "zendframework/zend-servicemanager:^3.0.3" ; fi
  - echo "composer.json to install:"
  - cat composer.json

install:
  - travis_retry composer install --no-interaction --ignore-platform-reqs

before_script:
  - .ci/mysql_fixtures_travis.sh
  - .ci/pgsql_fixtures.sh

script:
  - if [[ $EXECUTE_TEST_COVERALLS == 'true' ]]; then ./vendor/bin/phpunit --coverage-clover clover.xml ; fi
  - if [[ $EXECUTE_TEST_COVERALLS != 'true' ]]; then ./vendor/bin/phpunit ; fi
  - if [[ $EXECUTE_CS_CHECK == 'true' ]]; then ./vendor/bin/php-cs-fixer fix -v --diff --dry-run ; fi

after_success:

after_script:
  - if [[ $EXECUTE_TEST_COVERALLS == 'true' ]]; then ./vendor/bin/coveralls ; fi
